// src/components/layout/DashboardLayout.vue
<script setup>
import Sidebar from './Sidebar.vue'
import Header from './Header.vue'
</script>

<template>
  <div class="flex min-h-screen bg-slate-100 dark:bg-slate-950">
    <Sidebar />
    <div class="flex-1 ml-[260px]">
      <Header />
      <main class="p-6">
        <RouterView />
      </main>
    </div>
  </div>
</template>

// src/components/layout/DashboardLayout.jsx
import { Outlet } from 'react-router-dom'
import Sidebar from './Sidebar'
import Header from './Header'

export default function DashboardLayout() {
  return (
    <div className="flex min-h-screen bg-slate-100 dark:bg-slate-950">
      <Sidebar />
      <div className="flex-1 ml-[260px]">
        <Header />
        <main className="p-6">
          <Outlet />
        </main>
      </div>
    </div>
  )
}
