// src/components/dashboard/KpiCard.vue
<script setup>
import { computed } from 'vue'
import { TrendingUp, TrendingDown } from 'lucide-vue-next'
import { formatCurrency, formatNumber } from '@/utils'

const props = defineProps({
  title: String,
  value: [Number, String],
  change: Number,
  icon: [Object, Function],
  type: { type: String, default: 'number' },
  suffix: { type: String, default: '' },
})

const isPositive = computed(() => props.change >= 0)

const displayValue = computed(() => {
  if (props.type === 'currency') return formatCurrency(props.value)
  if (props.type === 'percent') return `%${props.value}`
  return `${formatNumber(props.value)}${props.suffix}`
})
</script>

<template>
  <div class="bg-white rounded-xl p-5 border border-slate-100 hover:shadow-md transition-shadow">
    <div class="flex items-start justify-between mb-4">
      <div class="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center">
        <component :is="icon" :size="20" class="text-primary" />
      </div>
      <div
        :class="[
          'flex items-center gap-1 text-xs font-medium px-2 py-1 rounded-full',
          isPositive ? 'bg-green-50 text-green-600' : 'bg-red-50 text-red-600'
        ]"
      >
        <TrendingUp v-if="isPositive" :size="12" />
        <TrendingDown v-else :size="12" />
        <span>{{ isPositive ? '+' : '' }}{{ change }}%</span>
      </div>
    </div>
    <p class="text-2xl font-bold text-slate-800">{{ displayValue }}</p>
    <p class="text-sm text-slate-500 mt-1">{{ title }}</p>
  </div>
</template>

// client/src/components/ui/KPICard.tsx
import type { LucideIcon } from 'lucide-react'
import { TrendingUp, TrendingDown } from 'lucide-react'

interface KPICardProps {
  icon: LucideIcon
  label: string
  value: string | number
  trend?: { value: number; isPositive: boolean }
}

export function KPICard({ icon: Icon, label, value, trend }: KPICardProps) {
  return (
    <div className="bg-bg-secondary border border-border-subtle rounded-xl p-5">
      <div className="flex items-center gap-2 mb-3">
        <div className="w-9 h-9 rounded-lg bg-accent-subtle flex items-center justify-center">
          <Icon size={18} className="text-accent" />
        </div>
        <span className="text-text-muted text-[13px]">{label}</span>
      </div>
      <div className="flex items-end justify-between">
        <span className="text-[28px] font-bold text-text-primary leading-none">{value}</span>
        {trend && (
          <span className={`flex items-center gap-1 text-xs font-medium ${trend.isPositive ? 'text-green-400' : 'text-red-400'}`}>
            {trend.isPositive ? <TrendingUp size={14} /> : <TrendingDown size={14} />}
            %{Math.abs(trend.value)}
          </span>
        )}
      </div>
    </div>
  )
}
